---
title: "My takeaways from the editorial:  “Moving to a World Beyond ‘p < 0.05”"
---

As a first-year PhD student in Epidemiology and Biostatistics, I have read numerous epidemiological papers, most of which explain effect sizes as insignificant or more often, due to publication bias, as significant. The authors of the editorial, “Moving to a World Beyond ‘p \< 0.05’”, challenge this practice and they’re right to do so. Why are we basing the importance of research based on an arbitrary dichotomization of a measure. Why do we look at 0.051 and 0.049, two very similar numbers as meaningfully different in interpretation?

The editorial recommends ATOM: “Accept uncertainty. Be thoughtful, open, and modest.”, and makes several important points about p-values, a few of which I will discuss here. 

For instance, the authors discuss how we use p-values to make definitive claims that an effect is significant or not. We need to be more open to uncertainty in our findings which in turn opens up room for improving our designs and analysis. I think we often want to publish a paper showing that we found an effect, but we need to be more open to admitting that we see an effect but we don’t know for certain that that effect truly exists and we need to explore it more. One paper showing a significant p-value is not enough to make a conclusion; we need to see results replicated. 

We also need to think about how meaningful our results are, significant or not. We can use a p-value and say that we see a significant effect, but does a significant effect really matter if the effect size is not meaningful? As some authors argue, we need to first clarify what effect size is meaningful before we conduct a study and not base it off of what we find after conducting a study as this may include an overreliance on p-value instead of meaningful results. 

Going off of this, the authors also discuss how when we look at p-values, we often see it as the most important part of our analysis and we think of other measures and implications as less important. Things like study design, analytic techniques, clinical importance, and confidence intervals take a backseat to p-values, whereas we could better understand an effect by looking more holistically. 

Overall, p-values can no longer be the most important thing we look at during analysis. Sure, we can consider it, but we definitely cannot dichotomize it to make a statement. 

\

Reference:

Wasserstein, R. L., Schirm, A. L., & Lazar, N. A. (2019). Moving to a World Beyond “p \< 0.05.” The American Statistician, 73(sup1), 1–19. https://doi.org/10.1080/00031305.2019.1583913

\
\
